"""Add status column

Revision ID: 7c23bf239804
Revises: a0603e356d5a
Create Date: 2025-06-21 17:35:48.003591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c23bf239804'
down_revision: Union[str, None] = 'a0603e356d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_refactorings', sa.Column('status', sa.String(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_refactorings', 'status')
    # ### end Alembic commands ###
