"""Create code refactoring tables

Revision ID: ef24bee47402
Revises: 
Create Date: 2025-06-17 16:20:58.799817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef24bee47402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_refactorings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_code', sa.Text(), nullable=False),
    sa.Column('refactored_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_refactorings_id'), 'code_refactorings', ['id'], unique=False)
    op.create_table('refactoring_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refactoring_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['refactoring_id'], ['code_refactorings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refactoring_feedback_id'), 'refactoring_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refactoring_feedback_id'), table_name='refactoring_feedback')
    op.drop_table('refactoring_feedback')
    op.drop_index(op.f('ix_code_refactorings_id'), table_name='code_refactorings')
    op.drop_table('code_refactorings')
    # ### end Alembic commands ###
